name: "dpkg CI"
on: 
  push:
    branches:
      - main 
      - master
  pull_request:
    branches: 
      - '*'
jobs:
  macOS:
    name: Build on  macOS
    runs-on: macos-latest
    env:
      INSTALL_PREFIX: /opt/local
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./build.sh
      - name: Test
        run: $INSTALL_PREFIX/bin/dpkg --version

